name: Main

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2.1.2
      
      - run: |
          npm ci
          npm run build
          
      - run: npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
        env: 
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - run: |
          npm version minor
          node scripts/set-version-hash
          npm publish --tag dev
