name: Main

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2.1.2
      
      - name: Install and build
        run: |
          npm ci
          npm run build
          
      - name: Set config
        run: npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
        env: 
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          
      - name: Increment minor version
        run: npm version minor
        continue-on-error: true

      - name: Clean up
        run: git reset --hard

      - name: Set prerelease to commit hash
        run: node scripts/set-version-hash
        
      - name: Publish
        run: npm publish --tag dev
