name: Main

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2.1.2
      
      - run: npm ci
      - run: npm run build
          
      - run: npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
        env: 
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - run: git reset --hard
          
      - run: npm version minor
        continue-on-error: true

      - run: node scripts/set-version-hash
      - run: npm publish --tag dev
