name: Publish dev

on:
  push:
    branches:
    - main

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: 14

    - name: Configure git credentials
      run: |
        git config --global user.email "github-action@users.noreply.github.com"
        git config --global user.name "Github Action"

    - name: Install and build
      run: |
        npm ci
        npm run build

    - name: Set config
      run: npm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}

    - name: Set version
      run: node scripts/version-dev

    - name: Publish
      run: npm publish --tag dev
